AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  IAM_Role:
    Description: The IAM role for the lambda function.
    Type: String
  ENCRYPTED_SMARTSHEET_ACCESS_TOKEN:
    Description: Your SmartSheet API access token; KMS encrypted and Base64 encoded.
    Type: String
    MinLength: '4'
    AllowedPattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
    ConstraintDescription: Must be a valid Base64 encoded string.
  SHEET_ID:
    Description: The sheet ID of the SmartSheet to be synced to the DynamoDB database table.
    Type: String
    AllowedPattern: '[0-9]*'
    ConstraintDescription: Must be a string containing an integer.
  NEW_TABLE_DEFAULT_READ_CAPACITY_UNITS:
    Description: The default read capacity units to be set when creating new tables.
    Type: String
    Default: '2'
    AllowedPattern: '[0-9]*'
    ConstraintDescription: Must be a string containing an integer.
  NEW_TABLE_DEFAULT_WRITE_CAPACITY_UNITS:
    Description: The default read capacity units to be set when creating new tables.
    Type: String
    Default: '2'
    AllowedPattern: '[0-9]*'
    ConstraintDescription: Must be a string containing an integer.


Resources:
  TableSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: SmartSheet-to-DynamoDB Synchronization
      Handler: lambda.handler
      Runtime: python2.7
      CodeUri: .
      Timeout: 300
      Role: !Ref IAM_Role
      Environment:
        Variables:
          ENCRYPTED_SMARTSHEET_ACCESS_TOKEN: !Ref ENCRYPTED_SMARTSHEET_ACCESS_TOKEN
          SHEET_ID: !Ref SHEET_ID
          NEW_TABLE_DEFAULT_READ_CAPACITY_UNITS: !Ref NEW_TABLE_DEFAULT_READ_CAPACITY_UNITS
          NEW_TABLE_DEFAULT_WRITE_CAPACITY_UNITS: !Ref NEW_TABLE_DEFAULT_WRITE_CAPACITY_UNITS
      Events:
        WebhookCallback:
          Type: Api
          Properties:
            Path: /callback
            Method: post

  SyncedSheetsTable:
     Type: AWS::Serverless::SimpleTable
     Properties:
       PrimaryKey:
         Name: id
         Type: String
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
