AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  FunctionName:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python2.7
      CodeUri: .
      Description: SmartSheet-to-DynamoDB Synchronization
      Timeout: 300
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        WebhookCallback:
          Type: Api
          RestApiId:
          Properties:
            Path: /callback
            Method: post

  TableName:
     Type: AWS::Serverless::SimpleTable
     Properties:
       PrimaryKey:
         Name: id
         Type: String
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
