---
swagger: "2.0"
info:
  description: "RESTful JSON interface to the smartsheet-dynamodb-sync AWS microservices."
  version: "v0"
  title: "SmartSheet-to-DynamoDB Sync API"
  contact:
    name: "Chris Lunsford"
    email: "chrlunsf@cisco.com"
  license:
    name: "MIT; Copyright (c) 2017 Cisco Systems, Inc."
host: "virtserver.swaggerhub.com"
basePath: "/cmlccie/smartsheet-sync/v0"
tags:
- name: "admins"
  description: "Secured Admin-only calls"
- name: "webhooks"
  description: "API targets for webhook operations"
schemes:
- "https"
paths:
  /callback:
    post:
      tags:
      - "webhooks"
      summary: "receives webhook callbacks"
      description: "Callback target for SmartSheet Webhooks.  Receives SmartSheet\
        \ webhook callback requests."
      operationId: "WebhookCallback"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
definitions: {}
